app:
  host : 
  debug : true
middleware:
  secret : my-secret
db:
  mysql:
    user : root
    pass : 1q2w3e
    host : 127.0.0.1
    port : 3306
    dbname : myweb
    debug : true
  redis:
    host : 127.0.0.1
    port : 6379
wechat :
  user :
    appid :
    app-secret :
