app:
  host : 
  debug : true
middleware:
  secret : gin-web-lucus
db:
  mysql:
    user : root
    pass : root
    host : 127.0.0.1
    port : 3306
    dbname : test
    debug : true
  redis:
    host : 127.0.0.1
    port : 6379